In [4]:
import pandas as pd

df = pd.read_csv("C:\\Users\\matve\\OneDrive\\Рабочий стол\\CAR-PRICE-PREDICTION-WITH-MACHINE-LEARNING-main\\Data\\used_car_dataset.csv")

print(df.shape)
df.head()

(9582, 11)

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
0,Honda,City,2001,23,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000"
1,Toyota,Innova,2009,15,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000"
2,Volkswagen,VentoTest,2010,14,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999"
3,Maruti Suzuki,Swift,2017,7,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000"
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000"

In [9]:
features = [
    "Brand",
    "model",
    "Year",
    "kmDriven",
    "Transmission",
    "Owner",
    "FuelType"
]

target = "AskPrice"

In [10]:
print(df.isna().sum())

Brand            0
model            0
Year             0
Age              0
kmDriven        47
Transmission     0
Owner            0
FuelType         0
PostedDate       0
AdditionInfo     0
AskPrice         0
dtype: int64

In [11]:
print(df.dtypes)

Brand           object
model           object
Year             int64
Age              int64
kmDriven        object
Transmission    object
Owner           object
FuelType        object
PostedDate      object
AdditionInfo    object
AskPrice        object
dtype: object

In [13]:
df["kmDriven"] = (
    df["kmDriven"]
    .str.replace(" km", "", regex=False)
    .str.replace(",", "", regex=False)
)

df["kmDriven"] = pd.to_numeric(df["kmDriven"], errors="coerce")

df["AskPrice"] = (
    df["AskPrice"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df["AskPrice"] = pd.to_numeric(df["AskPrice"], errors="coerce")

In [14]:
print(df[["kmDriven", "AskPrice"]].head())
print(df[["kmDriven", "AskPrice"]].dtypes)

   kmDriven  AskPrice
0   98000.0    195000
1  190000.0    375000
2   77246.0    184999
3   83500.0    565000
4   45000.0    685000
kmDriven    float64
AskPrice      int64
dtype: object

In [15]:
print(df.isna().sum().sort_values(ascending=False))

kmDriven        47
model            0
Brand            0
Year             0
Age              0
Transmission     0
Owner            0
FuelType         0
PostedDate       0
AdditionInfo     0
AskPrice         0
dtype: int64

In [16]:
df = df.dropna(subset=["kmDriven"])

In [17]:
print(df.shape)
print(df.isna().sum())

(9535, 11)
Brand           0
model           0
Year            0
Age             0
kmDriven        0
Transmission    0
Owner           0
FuelType        0
PostedDate      0
AdditionInfo    0
AskPrice        0
dtype: int64

In [18]:
df = df.drop(
    columns=[
        "Age",
        "PostedDate",
        "AdditionInfo"
    ]
)

In [19]:
print(df.shape)
print(df.columns)
df.head()

(9535, 8)
Index(['Brand', 'model', 'Year', 'kmDriven', 'Transmission', 'Owner',
       'FuelType', 'AskPrice'],
      dtype='object')

,Brand,model,Year,kmDriven,Transmission,Owner,FuelType,AskPrice
0,Honda,City,2001,98000.0,Manual,second,Petrol,195000
1,Toyota,Innova,2009,190000.0,Manual,second,Diesel,375000
2,Volkswagen,VentoTest,2010,77246.0,Manual,first,Diesel,184999
3,Maruti Suzuki,Swift,2017,83500.0,Manual,second,Diesel,565000
4,Maruti Suzuki,Baleno,2019,45000.0,Automatic,first,Petrol,685000

In [ ]:
df.to_csv(
    "C:../data/cleaned_car_data.csv",
    index=False
)